# Generated by Django 6.1 on 2026-09-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='adress',
            new_name='address',
        ),
    ]
