# Generated by Django 6.1 on 2026-10-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualApp', '0003_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='dicount_type',
            new_name='discount_type',
        ),
    ]
